# app/build.gradle.kts
# fastlane/Fastfile


name: Build APK

on:
  push:
    paths:
      - .github/workflows/test.yml
      - fastlane/Fastfile
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTION_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

permissions:
  contents: read
  packages: read
  actions: write

jobs:
  # version:
  #   name: Calculate Version Name and Number
  #   uses: bitwarden/android/.github/workflows/_version.yml@main
  #   with:
  #     app_codename: "bwpm"
  #     # Start from 11000 to prevent collisions with mobile build version codes
  #     base_version_number: 11000
  #     version_name: ${{ inputs.version-name }}
  #     version_number: ${{ inputs.version-code }}
  #     patch_version: ${{ inputs.patch_version && '999' || '' }}
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3

      - name: Check out repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Android Build
        uses: ./.github/actions/setup-android-build

      - name: Decode Keystore
        run: |
          cd keystores
          echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 -d > kt.jksx

      # - name: Build
      #   run: bundle exec fastlane assembleDebugApks

      - name: Build
        env:
            SIGN_STORE_FILE: kt.jksx
            SIGN_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
            SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
            SIGN_KEY_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
        run: bundle exec fastlane assemblesigningApks


      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/OutAPK/
          find . -name "*.apk" -exec mv {} ${{ github.workspace }}/OutAPK/ \;

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitwarden

          path: ${{ github.workspace }}/OutAPK/*.apk
